server:
  port: 8110
spring:
  application:
    name: gateway
  lifecycle:
    timeout-per-shutdown-phase: 30s
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  cloud:
    gateway:
      routes:
      - id: workTime-signIn-route
        uri: lb://workTime-service
        predicates:
        - Path=/insertSignInInfo/**
        filters:
        - StripPrefix=2
      - id: workTime-getLocation-route
        uri: lb://workTime-service
        predicates:
        - Path=/getLocation/**
      - id: workTime-setLocation-route
        uri: lb://workTime-service
        predicates:
        - Path=/setLocation/**
        filters:
        - StripPrefix=2
      - id: worker-manage-route
        uri: lb://login-service
        predicates:
        - Path=/api/login/**
#        filters:
#        - StripPrefix=1
      - id: user-login-token
        uri: lb://userClient
        predicates:
        - Path=/api/validateToken/**
#        filters:
#        - StripPrefix=1
      discovery:
        locator:
          enabled: true
      globalcors:
          cors-configurations:
           '[/**]':
            allowed-origins:
            - "http://192.168.8.131:8120"
            allowed-methods:
             - GET
             - POST
             - PUT
             - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Set-Cookie"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: gateway
    prefer-ip-address: true
    
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    
    
